let currentRows=[];let currentLocation=null;let selectMap=null;let selectMarker=null;let debounceTimer=null;
const regionSearch=document.getElementById("regionSearch"),regionResult=document.getElementById("regionResult"),customCoord=document.getElementById("customCoord"),searchBtn=document.getElementById("searchBtn"),csvBtn=document.getElementById("csvBtn"),printBtn=document.getElementById("printBtn"),darkModeBtn=document.getElementById("darkModeBtn"),shareBtn=document.getElementById("shareBtn");
function init(){initDarkMode();initClock();initRegionSelect();initMap();applySharedParams();regionSearch.addEventListener("input",handleRegionInput);regionResult.addEventListener("change",handleRegionSelect);searchBtn.addEventListener("click",handleSearch);csvBtn.addEventListener("click",()=>downloadCsv(currentRows));printBtn.addEventListener("click",()=>window.print());darkModeBtn.addEventListener("click",toggleDarkMode);shareBtn.addEventListener("click",copyShareLink);handleSearch();}
function initClock(){updateCurrentTime();setInterval(updateCurrentTime,1000);}function updateCurrentTime(){document.getElementById("currentTime").textContent=`현재 시각: ${new Date().toLocaleString("ko-KR")}`;}
function initDarkMode(){const saved=localStorage.getItem("darkMode");document.body.classList.toggle("dark",saved==="on");darkModeBtn.textContent=saved==="on"?"라이트모드":"다크모드";}function toggleDarkMode(){document.body.classList.toggle("dark");const is=document.body.classList.contains("dark");localStorage.setItem("darkMode",is?"on":"off");darkModeBtn.textContent=is?"라이트모드":"다크모드";}
function initRegionSelect(){regionResult.innerHTML="";REGION_LIST.forEach((r)=>{const o=document.createElement("option");const loc={name:r.name,lat:r.lat,lon:r.lon,key:r.key,source:"local"};o.value=JSON.stringify(loc);o.textContent=r.name;regionResult.appendChild(o);});const d=REGION_MAP[DEFAULT_REGION_KEY];currentLocation={name:d.name,lat:d.lat,lon:d.lon,key:d.key,source:"local"};regionSearch.value=d.name;setRegionResultSingle(currentLocation);renderLocationInfo(currentLocation);}
function applySharedParams(){const p=new URLSearchParams(location.search);const lat=p.get("lat"),lon=p.get("lon"),name=p.get("name"),region=p.get("region");if(lat&&lon){currentLocation={name:name||"공유 좌표",lat:Number(lat),lon:Number(lon),key:"shared",source:"shared"};customCoord.value=`${currentLocation.lat},${currentLocation.lon}`;regionSearch.value=currentLocation.name;setRegionResultSingle(currentLocation);}else if(region&&REGION_MAP[region]){const r=REGION_MAP[region];currentLocation={name:r.name,lat:r.lat,lon:r.lon,key:r.key,source:"local"};regionSearch.value=r.name;setRegionResultSingle(currentLocation);}renderLocationInfo(currentLocation);}
function setRegionResultSingle(loc){regionResult.innerHTML="";const o=document.createElement("option");o.value=JSON.stringify(loc);o.textContent=loc.name;regionResult.appendChild(o);regionResult.value=o.value;}
function setRegionResultList(list){regionResult.innerHTML="";list.forEach((item)=>{const o=document.createElement("option");o.value=JSON.stringify(item);o.textContent=item.name;regionResult.appendChild(o);});if(list.length){regionResult.selectedIndex=0;currentLocation=list[0];}}
function handleRegionInput(){customCoord.value="";clearTimeout(debounceTimer);debounceTimer=setTimeout(async()=>{const k=regionSearch.value.trim();if(!k)return;const local=getRegionFromLocalKeyword(k);if(local){setRegionResultList([local]);return;}try{const geo=await searchRegionByWorker(k);if(geo.ok&&geo.results.length)setRegionResultList(geo.results.map(normalizeGeocodeResult));}catch(e){console.warn("지역 검색 실패:",e);}},500);}
function handleRegionSelect(){if(!regionResult.value)return;try{currentLocation=JSON.parse(regionResult.value);customCoord.value="";regionSearch.value=currentLocation.name;moveMapTo(currentLocation.lat,currentLocation.lon);updateWindyMap(currentLocation.lat,currentLocation.lon);renderLocationInfo(currentLocation);}catch(e){console.warn("지역 선택 파싱 실패:",e);}}
async function handleSearch(){searchBtn.disabled=true;searchBtn.textContent="조회 중...";try{const coord=parseCoordInput(customCoord.value);if(coord){currentLocation={...coord,key:"custom",source:"coordinate"};regionSearch.value=currentLocation.name;setRegionResultSingle(currentLocation);}if(!currentLocation){const d=REGION_MAP[DEFAULT_REGION_KEY];currentLocation={name:d.name,lat:d.lat,lon:d.lon,key:d.key,source:"local"};regionSearch.value=d.name;setRegionResultSingle(currentLocation);}regionSearch.value=currentLocation.name;renderLocationInfo(currentLocation);moveMapTo(currentLocation.lat,currentLocation.lon);updateWindyMap(currentLocation.lat,currentLocation.lon);const forecast=await fetchForecastFromWorker(currentLocation);currentRows=forecast.rows||[];renderSummary(forecast.summary||{});renderTable(currentRows);renderChart(currentRows);renderBrandInfo(forecast.brand,forecast.meta);console.log("API 상태:",forecast.status);}catch(e){console.error("예보 조회 실패:",e);alert(e.message||"예보 조회에 실패했습니다.");}finally{searchBtn.disabled=false;searchBtn.textContent="예보 조회";}}
function initMap(){const d=REGION_MAP[DEFAULT_REGION_KEY];selectMap=L.map("selectMap").setView([d.lat,d.lon],10);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18,attribution:"&copy; OpenStreetMap"}).addTo(selectMap);selectMarker=L.marker([d.lat,d.lon]).addTo(selectMap);selectMap.on("click",async(e)=>{const lat=Number(e.latlng.lat.toFixed(6)),lon=Number(e.latlng.lng.toFixed(6));let placeName="지도 선택 좌표";try{const reverse=await reverseGeocodeByWorker(lat,lon);if(reverse.ok&&reverse.name)placeName=reverse.name;}catch(err){console.warn("역지오코딩 실패:",err);}currentLocation={name:placeName,lat,lon,key:"map",source:"map"};customCoord.value=`${lat},${lon}`;regionSearch.value=placeName;setRegionResultSingle(currentLocation);moveMapTo(lat,lon);updateWindyMap(lat,lon);renderLocationInfo(currentLocation);});updateWindyMap(d.lat,d.lon);}
function moveMapTo(lat,lon){if(!selectMap||!selectMarker)return;selectMap.setView([lat,lon],10);selectMarker.setLatLng([lat,lon]);}
function copyShareLink(){if(!currentLocation){alert("공유할 위치가 없습니다.");return;}const url=new URL(window.location.href);url.search="";if(currentLocation.source==="local"&&currentLocation.key){url.searchParams.set("region",currentLocation.key);}else{url.searchParams.set("lat",currentLocation.lat);url.searchParams.set("lon",currentLocation.lon);url.searchParams.set("name",currentLocation.name);}navigator.clipboard.writeText(url.toString()).then(()=>alert("공유 링크가 복사되었습니다.")).catch(()=>prompt("아래 링크를 복사하세요.",url.toString()));}
document.addEventListener("DOMContentLoaded",init);
